### PR TITLE
[DOC] Add plantuml dependency, fix absolute paths

### PR DESCRIPTION
**Pull request by marusinp**
Add new dependency Plantuml ver. 1.2017.18. Used by Sphinx to generate UML diagrams.
Fix absolute paths in conf.py and other rst files with ::uml: elements (mentioned in uml.rst).

Signed-off-by: pmarusin <peto.marusin@gmail.com>

### CODE REVIEW

**Comment by BLigart** [comment]
OK, funguje to

**Comment by BLigart** [comment]
OK, funguje to

**Comment by BLigart** [comment]
OK, funguje to

**Review by skcmarek — APPROVED** [review]
tested with sphinx-build - all UMLs were generated

**Review by BLigart — APPROVED** [review]
tested, all umls generated successfully

**Pull request merged**
